# Generated by Django 5.2.3 on 2025-07-01 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soniHouseAgent', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Owner',
            new_name='landlord',
        ),
    ]
