# Generated by Django 5.2.3 on 2025-07-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soniHouseAgent', '0002_rename_owner_landlord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
