# Generated by Django 5.2.3 on 2025-07-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soniHouseAgent', '0003_alter_tenant_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landlord',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='phone_number',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone_number',
            field=models.CharField(max_length=7),
        ),
    ]
